### ISSUE TITLE
Kolibri Windows installer: "Kolibri application already running"

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installers#2]
Reporter is unable to run `kolibri manage createsuperuser`

![kolibri manage-error message](https://cloud.githubusercontent.com/assets/374612/24331643/d8331858-1238-11e7-909b-2acf0193197c.JPG)

Needs investigation quickly as it reportedly blocks usage on Windows.

**Comment by mrpau-richard** [comment]
Hi @benjaoming thanks for reporting this. I will work on it.

**Comment by mrpau-richard** [comment]
Hi @benjaoming I think you're looking at the wrong Kolibri exe file. The `exe` file you're using is the kolibri windows application. Use this `exe` path `C:\Python34\Scripts\kolibri.exe` to create a superuser.

**Comment by benjaoming** [comment]
Hi @mrpau-richard - I didn't report this :)

But BP Panwar updated us by email:

> Thank you for testing the issue on your PC and sending me the screenshot.  Your screenshot helped me to find the root cause of this problem.  I noticed that you have two copies of the Kolibri.exe.  One is in the folder "C:\Program Files\Kolibri\" created on 24th October 2016 and another one is in folder C:\Python34\.   As the Kolibri server is running from C:\Program Files\Kolibri\Kolibri.exe", I was trying to run the Kolibri with the parameters to create additional ‘superuser’ from the same folder. However after seeing the screenshot from you, I tried to run the Kolibri from the folder C:\Python34\Scripts and managed to create the additional superuser.

Does the update indicate that this is not an issue?

**Comment by mrpau-richard** [comment]
@benjaoming Yeah, I think this was not an issue. closing this.
